### ISSUE TITLE
Exponentiation over empty character not working

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#117]
In relation to https://github.com/metanorma/metanorma-bipm/issues/116

````
[stem%unnumbered]
++++
B_n(ii(rho)) = 1/{(n - 1)!} sum_{r=0}^n " "^n C_r (-1)^r (ii(rho) - r)_{+}^{n-1}
++++
````

renders

![issue7-generated](https://user-images.githubusercontent.com/33627611/109528855-7eb89180-7a8b-11eb-98fd-3305c71209be.PNG)

*Original:*
![issue7-original](https://user-images.githubusercontent.com/33627611/109528888-85df9f80-7a8b-11eb-964f-529d3d8cb91d.PNG)

**Comment by Intelligent2013** [comment]
@manuel489 this issue was fixed in the commit https://github.com/metanorma/mn-native-pdf/commit/b65dc2e68d7a92baf944de8e17d6da7bf0c0c498 (for https://github.com/metanorma/mn-native-pdf/issues/311).

Now it renders as:
![изображение](https://user-images.githubusercontent.com/5559926/109849226-2daec600-7c62-11eb-9ed0-29d9faabc406.png)

Here is resulted PDF (rendered in my environment (Feb, 28)) rendered by latest JCGM xslt: [document.presentation.pdf](https://github.com/metanorma/metanorma-bipm/files/6078103/document.presentation.pdf)

**Comment by manuel489** [comment]
Huh, I see. Thank you @Intelligent2013.
I'm closing then 👍
