### ISSUE TITLE
ZIP files from relaton-bipm are breaking my rspec with VCR

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-bipm#181]
https://github.com/metanorma/metanorma-bipm/runs/7167812615?check_suite_focus=true

I have emended my rspec to deal with this, as you have had to:

spec/metanorma/base_spec.rb

````
    expect(File).to receive(:exist?).with(/index\.yaml/).and_return false
    allow(File).to receive(:exist?).and_call_original
    VCR.use_cassette "bipm", match_requests_on: %i[method uri body] do
````

However, one of the two references in one of the two files is consistently failing to fetch. This does not happen locally, and this does not happen in the French test.

**Comment by andrew2net** [comment]
> https://github.com/metanorma/metanorma-bipm/runs/7167812615?check_suite_focus=true

@opoudjis I don't see any issues related to getting `index.zip` in the log.

> expect(File).to receive(:exist?).with(/index\.yaml/).and_return false
> allow(File).to receive(:exist?).and_call_original

The idea of the stubbing `File.exist?` method is to make VCR records the `index.zip` getting HTTP request.
In case the local `index.yaml` exists relaton-bipm doesn't make the request to get `index.zip`, so the test fails on GHA running because container doesn't have the `index.yaml` file and relaton-bipm trying to get `index.zip` but VCR doesn't have record for the request.

> VCR.use_cassette "bipm", match_requests_on: %i[method uri body] do

The `match_requests_on` argument is used for ISO async test because it makes requests with differences in body only.
I had an issue with an async test in BIPM as it makes many `index.zip` requests and tried to solve the issue setting the argument. It doesn't help but I forgot to remove the `match_requests_on` from the test.
To make VCR allow multiple identical requests it needs to setup `allow_playback_repeats: true` parameter. For example in spec_helper:
```ruby
VCR.configure do |c|
  c.cassette_library_dir = "spec/vcr_cassetes"
  c.default_cassette_options = {
    clean_outdated_http_interactions: true,
    re_record_interval: 7 * 24 * 3600,
    record: :once,
    allow_playback_repeats: true,
  }
  c.hook_into :webmock
end
```
Maybe it possible to use the `allow_playback_repeats: true` in a single test, I haven't tried it yet.
