### ISSUE TITLE
Font usage in BIPM layout

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-bipm#2]
In BIPM pdf layout a lot of fonts are being used. Can we decrease number of fonts used?

These fonts are using in BIPM layout:
- WorkSans fonts (are using for title page only)
WorkSans-Thin - 1st of title in French
WorkSans-ExtraLight - 2nd line of title in French
WorkSans-Light - 3rd line of title in Frencg
WorkSans-Regular - 4th line, and edition number
WorkSans-Medium - 5th line of title (1st in English)
WorkSans-Semibold - 6th line of title (2nd in English)
WorkSans-Bold - 7th line of title (3rd in English)
WorkSans-ExtraBold - 8th line of title (4th in English)
![изображение](https://user-images.githubusercontent.com/5559926/92302190-d9f14780-ef72-11ea-8ac7-b42735b2f768.png)

- Fonts for mathematical glyphs (examples):

   - BookAntiqua-Italic

![изображение](https://user-images.githubusercontent.com/5559926/92302250-508e4500-ef73-11ea-836c-3bf3ae8d230a.png)
(page 29 in in SI-Brochure-9.pdf )

   - BookmanOldStyle-Italic

![изображение](https://user-images.githubusercontent.com/5559926/92302279-a82cb080-ef73-11ea-9103-cad85c4539cf.png)
(page 29 in in SI-Brochure-9.pdf )

(note that two chars 'v' (hex 76) has a different glyphs)

   - Calibri

![изображение](https://user-images.githubusercontent.com/5559926/92302354-3ef96d00-ef74-11ea-863e-2a46d908f2ca.png)
(Tableau 6, page 30 in SI-Brochure-9.pdf )

   - CambriaMath

![изображение](https://user-images.githubusercontent.com/5559926/92302393-7ff18180-ef74-11ea-96bc-2b732056b5d2.png)
(page 21 in SI-Brochure-9.pdf )

- MonotypeCorsiva

![изображение](https://user-images.githubusercontent.com/5559926/92302438-e080be80-ef74-11ea-9587-eb3a7b58fdaf.png)
(page 21 in SI-Brochure-9.pdf )

- Main section font - TimesNewRoman - can be used as is.
- Annex 1 preface (conference decisions) - Arial - can be used as is.

- unordered list item mark - SymbolMT, Courier - can be replaced to free font

- Wingdings-Regular - quad char (page 50 for example) - can be replaced to free font.

**Comment by ronaldtse** [comment]
@Intelligent2013 I have consulted BIPM, let's see what they say.

We will want to minimize the fonts used to simplify requirements needed to compile the PDF.

There are few categories of fonts which we can discuss separately:

1. Title page. The WorkSans font variants are only used for the title page, where each line out of 8 uses a different WorkSans font. _This is fine since WorkSans is an openly licensed font._

2. Body text. Body text is in Times New Roman. Interestingly, Appendix 1 uses Arial. This is fine, but was wondering: _Can we apply Times New Roman across the body as well as all Appendices?_

3. Punctuation and spaces. The unordered list item mark uses Symbol MT and Courier interchangeably. _We will replace that with single font._ Some empty unicode spaces uses Wingdings. _We will replace those with normal unicode spaces with a font already in use._

4. Math fonts. In various places, different fonts are used for math. This includes Cambria, Cambria Math, Book Antiqua,  Bookman Old Style, Monotype Corsiva, Calibri. This is where we need help.
In Table 5, the symbol for “speed, velocity” and “specific volume” are both represented by the same character “v” in different fonts. Typically “speed, velocity” uses the character “v”, but “specific volume” is usually represented by the “nu” character. _We propose to replace the "specific volume” “v” with a proper “nu”._ You can see the rendering difference below via AsciiMath. _For Math fonts, we propose to unify all math symbols to use a single math font. The best choice here is Cambria Math because it has the most comprehensive math character set._

<img width="449" alt="image" src="https://user-images.githubusercontent.com/11865/92308429-0d15f400-efd0-11ea-9811-6b39e438d76e.png">

**Comment by ronaldtse** [comment]
> 2. You can apply Times New Roman across the body and the appendices
> 3. OK

4 in discussion.

**Comment by ronaldtse** [comment]
Regarding item 4, from the authoritative source:

> With respect to the symbols for velocity and specific volume, both should be lowercase “v” in italics. I don’t mind if they look the same.

So we will use lowercase "v" in italics for both.

**Comment by ronaldtse** [comment]
All done, closing.
