### ISSUE TITLE
Custom sequence markup in ordered list

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#24]
*From https://github.com/metanorma/bipm-si-brochure/issues/24*

The custom sequence in ordered lists based on manually numbering the list items is not working in Metanorma (and apparently, in AsciiDoc neither).

````
...

1. the base units, the supplementary units and the derived units of the Système International d'Unités, which form a coherent set, are denoted by the name "SI units"; footnote:[The CIPM approved in 2001 a proposal of the CCU to clarify the definition of "SI units" and "units of the SI", see <<cipm-si-units>>.]

2. the prefixes adopted by the CGPM for the formation of decimal multiples and submultiples of SI units are called "SI prefixes";

and *recommends*

3. the use of SI units and of their decimal multiples and submultiples whose names are formed by means of SI prefixes.
````

*Output*:

![issue13-generated](https://user-images.githubusercontent.com/33627611/96019817-14c08800-0e1b-11eb-9699-17609560762f.PNG)

**Comment by Intelligent2013** [comment]
> @Intelligent2013 I will also need to decide whether the sequence choice on lists is something we should implement independently, or something I should pass on to you as attributes on each `<ol>`. My inclination is still that we should implement it independently.

@opoudjis sorry for my misunderstanding, what does mean 'independently'? If xml will contain initial value, then I can set it for PDF out, if not, then each list will start with '1' always (where can I get the information then?).
Notes for xml format:
1. attribute can be set only for lists which have non '1' first value.
2. attribute can be set for each `li` instead of parent `ol`.
3. for aphabetical numbering, it would be better if the start value will be set as `3`, not `c`.

**Comment by opoudjis** [comment]
Sorry, @Intelligent2013, this is not about the start value (which I am refusing to implement for now, because it will involve major refactoring for Word); it is about the style, `<ol type="a">` v s `<ol type="1">`. Right now there is a metanorma default: the levels go a, 1, i, A, I. In BIPM ordered lists will presumably start with 1 at the first level, but I will need to look through the documents to confirm.

The question for you is: should I give you  `<ol type="xxx">` populated for all `ol` in the documents of BIPM? Or should we both implement a different sequence of levels in the rendering code independently?

**Comment by Intelligent2013** [comment]
> The question for you is: should I give you <ol type="xxx"> populated for all ol in the documents of BIPM? Or should we both implement a different sequence of levels in the rendering code independently?

I can implement in xslt any rules for types of ol depends on the nested level and position in hierarchy. So don't need to populate type attribute.

**Comment by opoudjis** [comment]
The default list style is arabic; but the festival of historical folly that is Annex 1 includes:

1st CGPM: A. then 1.

CIPM 2002: a) as two levels nested down from unordered list

24th CGPM: (i) as three levels down from unordered list, but not rendered as indented list at all

This means that we do in fact need to permit arbitrary list types. 

Now it turns out that we do insert the `ol/@type` into the XML; we've just been ignoring them in rendering, because that's been Metanorma policy. @Intelligent2013, you and I will both need to not ignore  `ol/@type` for BIPM.

**Comment by opoudjis** [comment]
Note: there is grotesque and execrable incoherence in BIPM publications on formatting of list numbers: 1., a), (1). 

Metanorma is not in the business of perpetuating formatting incoherence. We will be rendering list numbers only one way.
