### ISSUE TITLE
(URGENT) Brochure: Too much horizontal separation between table number and caption

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-bipm#301]
*Issue found in https://github.com/metanorma/bipm-si-brochure/pull/213*

This issue only applies to English version. The French version is correct.

Generated:
![issue-1-generated](https://user-images.githubusercontent.com/33627611/234949251-249fcfa7-1e76-4f48-8992-5cc2d96f89a0.PNG)

Original:
![issue-1-original](https://user-images.githubusercontent.com/33627611/234949462-2a25d6a6-f5cf-43fe-9b47-a960aa161368.PNG)

(Sorry, didn't notice this issue before.)

**Comment by Intelligent2013** [comment]
@manuelfuenmayor there is a difference between styles in the original 'fr' and 'en' parts.
Original PDF (en) - there isn't indent between table number and caption, the caption continues on the next line _under_ the table number:
![image](https://user-images.githubusercontent.com/5559926/234963288-0c387c8a-494f-46df-93e1-aaf451663201.png)

Origianal PDF (fr) - there is indent between table number and caption, the caption continues on the next line with left indent:
![image](https://user-images.githubusercontent.com/5559926/234963514-89f28c1d-6f14-41f0-8268-d4226cf57e30.png)

BIPM XSLT was developed based on 'fr' styles (therefore you wrote 'The French version is correct.').

@ronaldtse should we support two styles - for 'en' and 'fr' ?

Actually there are a lot of differences between 'fr' and 'en', for instance:
- initial page
![image](https://user-images.githubusercontent.com/5559926/234964997-5901bc02-da75-4f71-a764-84b5def7bdf6.png)
![image](https://user-images.githubusercontent.com/5559926/234965035-eb8f8380-fa60-4638-873a-9bdd66c085e3.png)

- the distance between 1st level section number and title
![image](https://user-images.githubusercontent.com/5559926/234965153-1c1a4f28-77ac-4bc9-b2be-baa18aac7e4c.png)
![image](https://user-images.githubusercontent.com/5559926/234965192-580a2496-e838-42db-a093-fcb00c92ef3f.png)

- the space before table
![image](https://user-images.githubusercontent.com/5559926/234965485-7192f68f-95fd-420f-9d5d-f9cce510019c.png)
![image](https://user-images.githubusercontent.com/5559926/234965542-98264d00-9324-4c7b-acdc-b9ee25c3beff.png)

- ...

Should we support them? If yes, then I need the documentation about all BIPM rules/styles, because visual human checking can't find all rendering rules.

**Comment by ronaldtse** [comment]
> @ronaldtse should we support two styles - for 'en' and 'fr' ?

No. We should follow what the BIPM says is correct, which is the French version.

So this issue can be closed. Thanks @manuelfuenmayor @Intelligent2013 !

**Comment by ronaldtse** [comment]
The comparison of the files should NOT be against the original, it should be against the last version we sent to the BIPM for verification, because they already approved that version.
