### ISSUE TITLE
Support for "JCGM" prefix in citation of JCGM documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#350]
```
[relaton] `JCGM 101:2008` does not have a recognised prefix
```

Depends on:
* https://github.com/relaton/relaton-bipm/issues/57

**Comment by andrew2net** [comment]
Fixed in v1.16.5
- [format](https://github.com/relaton/relaton-bipm#reference-structures-for-outcomes-documents) for meeting references should be like `JCGM Meeting 101 (2008)`
- There is no 101 meeting in the [bipm-data-outcome](https://github.com/metanorma/bipm-data-outcomes/tree/main/jcgm/meetings-en) dataset
```sh
$ relaton fetch --no-cache 'JCGM Meeting 11 (2006)'
[relaton-bipm] (JCGM Meeting 11 (2006)) Fetching from Relaton repository ...
[relaton-bipm] (JCGM Meeting 11 (2006)) Found: `JCGM 11st Meeting (2006)`
<bibdata type="proceedings" schema-version="v1.2.4">
  ...
```
