### ISSUE TITLE
Multi-paragraph footnotes

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-bipm#62]
CIPM-MRA D-02 document contains multi-paragraph footnote. Can we produce this in Metanorma?

![image](https://user-images.githubusercontent.com/55683568/98872902-adc4dc00-2477-11eb-8633-2ebdc1573593.png)

**Comment by manuel489** [comment]
In addition, I posted a similar question in https://github.com/metanorma/metanorma-standoc/issues/373.

**Comment by opoudjis** [comment]
Oh, @anermina...

https://github.com/metanorma/metanorma-iso/issues/49

Asciidoc *refuses* to suppport multi-paragraph footnotes. Because Asciidoc designers pay more attention to a single American styleguide, than to five centuries of typographical practice. @manuel489 that impacts https://github.com/metanorma/metanorma-standoc/issues/373 as well.

There is a simple work-around, which said Asciidoc designer suggests: injecting line-breaks instead of paragraphs. That won't address Manuel's concern.

There is a second work-around, which I had not realised when I investigated this two years ago: to define a new multi-paragraph footnote macro. That will address both your requirements. It will not be vanilla Asciidoctor, but Metanorma has moved a fair distance away from vanilla Asciidoctor a long time ago.

I think that is preferable, and I propose to implement it under this ticket. Until I do so, Nermina, use the line breaks as a workaround. (Manuel, you can't.)

**Comment by opoudjis** [comment]
The catch is, we can't insert a multiple block macro inline inside a paragraph. The Asciidoctor processing model won't cope with it. The workaround of injecting `pass:p[ +]` certainly won't cope with anything like a table.

What we need to do, baroque though it is, is insert a footnote marker, insert footnote text as a separate block (which we'll make a note), and bind them together in postprocessing. So:

````
This is a paragraph.footnote-block:[id1] This continues the paragraph.

[[id]]
[NOTE]
--
This is

a multi-paragraph

footnote
--
````
