### ISSUE TITLE
Issue related with `nofetch` option in bibliography references

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#69]
When `nofetch` option is used in bibliography references, the  "flavor acronym" and the "identifier" gets included at the beginning of the main text of the reference.
For example:

````
* [[[bipm-8,nofetch(BIPM SI Brochure)]]] BIPM, The International System of Units (SI Brochure) [8^th^ edition, 2006], https://www.bipm.org/en/publications/si-brochure/.
````

Results as
![Capture1](https://user-images.githubusercontent.com/33627611/99445034-644f1380-28f3-11eb-8fd5-d791eb9995b8.PNG)

Is this a deliberate result?

(Currently, BIPM is requiring to show the main text of the reference exactly as it is shown in the original source.)

**Comment by opoudjis** [comment]
We have standard behaviour that the document identifier type and document identifier must prefix references, if available; e.g. _ISO 3166, Country Codes_: [ISO] [3166], [Country Codes].

That behaviour is correct behaviour.

We have several issues here:

1. BIPM are the antithesis of decent bibliographic practice, and document identifiers are unknown to them. That does not mean they get to ignore real SDO's identifiers if they get included in a bibliography. But if we allow them to persist in ignorance of document identifiers (which we should not), then we will need to omit any BIPM document identifiers in BIPM bibliographies.
2. Because document identifiers are unknown to BIPM, we don't have a real document identifier for them, apart from the document identifier we have been forced to make up, "BIPM SI Brochure". That will of course look odd when used in place of a real document identifier.
3. standoc is being naive in its treatment of `nofetch()` : it recognises "BIPM SI Brochure" as a BIPM document identifier, but it encodes it as `<docidentifier type="BIPM">BIPM SI Brochure</docidentifier>`, which means it gets rendered as [BIPM]  [BIPM SI Brochure]. `nofetch()` needs to strip BIPM from the start of the document identifier, if it knows that it will be prefixed to the document identifier in rendering.

I will fix 3. I may address 1. But BIPM's expectation that references must be rendered exactly as data entered, and not take benefit of relaton to generate correct and consistent bibliographic citations, is retrograde.

**Comment by manuel489** [comment]
Well, I opened this ticket motivated from this BIPM's feedback:

> 13 | reference [1]: replace with original text

But maybe we could ask to BIPM if they can overlook the prefixed identifier to avoid additional work?

Of course, a workaround is to not use `nofetch()` at all (i.e. `* [[[x,1]]]`) and the original text would render as it is. But I don't know if we would be profaning semantics in that case.

**Comment by opoudjis** [comment]
Hmm, I'll have to think about this. Do they have a coherent bibliographic style, that you've seen? Do they cite other standards, and if they do, what do they do with those standards' identifiers?

**Comment by opoudjis** [comment]
I'm going to bite the bullet, and decline to prefix a document identifier with the SDO type, if it already is prefixed with it.

**Comment by opoudjis** [comment]
This citation in MeP 3:

````
* [[[iso5436,ISO 5436-1:2000]]] ISO 5436-1:2000 Geometrical Product Specifications (GPS) -- Surface texture: Profile method; Measurement standards -- Part 1: Material measures

* [[[iso25178,ISO 25178-70:2014]]] ISO 25178-70:2014 Geometrical product specification (GPS) -- Surface texture: Areal -- Part 70: Material measures
````

indicates that BIPM indeed prefix SDO identifiers to standards, and this is in fact an ISO-style formatted reference, though with no comma between identifier and title.

For better or worse, we have made up the BIPM identifiers, and we will have to omit them from rendering within the BIPM flavour.

**Comment by opoudjis** [comment]
@manuel489 Because ISO reference are represented correctly, I request that you henceforth remove all ISO identifiers from the start of bibliographic references, since they will continue to be added automatically.
