### ISSUE TITLE
Special footnote type in JCGM document

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-bipm#92]
*In relation with https://github.com/metanorma/mn-samples-bipm/issues/20*

[JCGM_100_2008_E.pdf](https://github.com/metanorma/mn-samples-bipm/files/5601382/JCGM_100_2008_E.pdf) includes a special footnote type (besides the usual one) tagged as "*Footnote to the 2008 version*":

![special-footnote3](https://user-images.githubusercontent.com/33627611/102679454-67ede880-4186-11eb-9e71-3e20076e8566.PNG)

I'm encoding it as normal footnote in the meanwhile.
Assuming that there should be a particular markup for this case, right?

**Comment by ronaldtse** [comment]
It feels like a normal footnote to me. We will clarify whether it needs any special treatment. I do note that some publications do this...

**Comment by opoudjis** [comment]
Occasionally documents do come up with different footnote markers for different purposes. And since BIPM appears to be the repository of all stylistic and typographic inconsistency in scientific typesetting, it is inevitable they too would use it. Not that Word makes it easy for them to: https://word.tips.net/T000541_Inserting_Footnotes_Using_Custom_Footnote_Marks.html

Yes, we can support custom footnote marks by altering markup and defining a brand new macro. No, I don't think we should do so. And we do have to say Stop to the endless sequence of formatting indulgence of this flavour soon.

**Comment by ronaldtse** [comment]
@opoudjis I don't think we should have this "special footnote type" since it doesn't really mean much. They could have included the text "Footnote to this edition" instead of the footnote anyway and the semantics do not get affected.

**Comment by opoudjis** [comment]
@manuel489 That means we are not proceeding with this ticket.
