### ISSUE TITLE
Proper handling of upright/italicized math symbols in BIPM documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#93]
Questions from @anermina / @opoudjis :

From our encoding and analysis of the SI Brochure and all MEPs, we noticed that most Greek letters are italicized, but there are exceptions:

1. Δ is never italicized
 
2. π is sometimes italicized
a) In the French SI Brochure:
![image002](https://user-images.githubusercontent.com/11865/102760384-64d64080-43b0-11eb-92b1-af95dfa7d19e.png)

b) In the MEP Candela
![image004](https://user-images.githubusercontent.com/11865/102760400-69025e00-43b0-11eb-9f27-e024ea479257.png)
and
![image006](https://user-images.githubusercontent.com/11865/102760407-6b64b800-43b0-11eb-9955-9efd4e41d7e5.png)

In the case of π, it seems that it is italicized when used together with a unit, but not italicized when it is represented as a standalone number. Are a) and b) due to inconsistent practice, or has this to do with units? 

--------

Response from BIPM:

The examples you give for the different writings of π in the SI brochure are due to inconsistencies. When π stands for the number 3.141…, as it is always the case in the brochure, it should always be written in upright font, never in italics.
 
The general rule for the use of italics or roman font is described in ISO 80000-1:2009 (Quantities and Units, Part 1), section 7. Symbols (not only Greek) which stand for a quantity are printed in italics. Symbols which stand for a unit are printed in roman type. Symbols like π and e (Euler’s number) stand for pure numbers and are written in roman font, too. If e stands for the elementary charge, it stands for a quantity and would be printed in italics: e.

The Δ stands for ‘difference’ and is in general printed in upright font.

--------

Comment:

Since this relates to ISO 80000-1:2009, perhaps we should make this available throughout Metanorma.

**Comment by opoudjis** [comment]
Well, this is clearly not mathematical typesetting, but something else. 

* The defaults of English typesetting using italics for all Greek letters, and French using upright letters for all Greek letters, is not contradicted here. This is a completely different convention.
* MathML in fact *almost* has this convention. Things in `<mn>` (numbers) are upright, things in `<mi>` (variables) are italics.
* This suggests that we misunderstood the convention at work, and need to abide by English practice (things that are mi are always italics).
* However NOTHING in AsciiMath expresses the mi/mn distinction. _And nothing should._ It would be a perversion of that notation.
* And it would be a complete waste of time for us to try to make it do so now, when the notation is likely to change anyway.

Not to be fixed now. At all. When we have Units notation, we can revisit this.

And unless you want editors to start inserting actual MathML into their documents, so that they can force the mn/mi distinction, the only thing they can do is italics/upright styling.

**Comment by opoudjis** [comment]
I'm unassigning myself. There is nothing to be done at this time.

**Comment by anermina** [comment]
Assigning myself... I will check the rest of the BIPM documents which are in repos other than bipm-si-brochure.

**Comment by anermina** [comment]
Changes for the documents from `mn-samples-bipm` repository are made in https://github.com/metanorma/mn-samples-bipm/pull/26.

**Comment by opoudjis** [comment]
Ok, with the understanding that eventually, we will need to change the markup completely, to something that does understand the difference between unit e and numeral e (either raw MathML, or some blend of AsciiMath and UnitsML). https://github.com/metanorma/metanorma-bipm/issues/3

**Comment by opoudjis** [comment]
This is not quite addressed yet by #3, because unitsml currently only includes SI units, and not base SI quantities.

**Comment by opoudjis** [comment]
I am assigning myself this now, because we will need to come up with something for base SI quantities: either we keep them as `rm(e)`, or we incorporate them into the unitsml processor. I strongly prefer the former.

**Comment by opoudjis** [comment]
From https://github.com/metanorma/bipm-si-brochure/issues/121 , there is a request to support explicit sans serif rendering of dimensions as Plane 1 characters, rather than sans serif ascii characters. While this is still overkill, it is true that the symbols are already encoded in the dimensions.yaml file of asciimath2unitsml, but as ascii, not Plane 1.

So we will add support for entry of both dimensions and fundamental units into asciimath2unitsml (though it is scope creep), with appropriate constant names for each; these can enter into mathematical expressions, but cannot be preceded by numbers.

**Comment by ronaldtse** [comment]
e.g. electric current: 1D5A8 (letter I).

**Comment by opoudjis** [comment]
Fundamental units are already supported:

````
c.Asciimath2UnitsML('"unitsml(e)"')
````

````
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mrow xref="U_NISTu246"><mi mathvariant="italic">e</mi></mrow>

<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_NISTu246">
<UnitSystem name="not_SI" type="not_SI" xml:lang="en-US"/>
<UnitName xml:lang="en">atomic unit of charge</UnitName>
<UnitSymbol type="HTML"><i>e</i></UnitSymbol>
<UnitSymbol type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><mi mathvariant="italic">e</mi></mrow></math>
</UnitSymbol>
</Unit>


<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTd17">
<Time symbol="T" powerNumerator="1"/>
<ElectricCurrent symbol="I" powerNumerator="1"/>
</Dimension>


<Quantity xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTq22" dimensionURL="#NISTd17" quantityType="base">
<QuantityName xml:lang="en-US">electric charge</QuantityName>
</Quantity>

</math>
````

The dimensions will be supported as dim_XXX, e.g. dim_I (dimension I) for electric current.

**Comment by opoudjis** [comment]
Implemented. So, @manuel489 @anermina 

If there is a dimension to be encoded, it shall be `unitsml(dim_XXX)`:

 |dim_L | Length
 |dim_M | Mass
 |dim_T | Time
 |dim_I | Electric Current
 |dim_Theta | Thermodynamic Temperature
 |dim_N | Amount of Substance
 |dim_J | Luminous Intensity
 |dim_phi | Plane Angle (dimensionless)

The fundamental units should *already* be supported; e.g. `unitsml(e)` already works for the fundamental amount of charge. Consult https://github.com/plurimath/asciimath2unitsml/blob/main/README.adoc, towards the bottom of the final table.
